// packages/react/src/DayFlowCalendar.tsx
import { CalendarRenderer } from '@dayflow/core';
import type {
  ICalendarApp,
  CustomRendering,
  UseCalendarAppReturn,
  EventContentSlotArgs,
  EventDetailContentProps,
  EventDetailDialogProps,
  CreateCalendarDialogProps,
  TitleBarSlotProps,
  ColorPickerProps,
  CreateCalendarDialogColorPickerProps,
} from '@dayflow/core';
import { useRef, useEffect, useLayoutEffect, useState, useMemo } from 'react';

// useLayoutEffect on the client fires before paint; fall back to useEffect on
// the server to avoid SSR hydration warnings (the calendar is client-only anyway).
const useIsomorphicLayoutEffect =
  typeof window === 'undefined' ? useEffect : useLayoutEffect;
import type { ReactNode, FC } from 'react';
import { createPortal } from 'react-dom';

export interface DayFlowCalendarProps {
  calendar: ICalendarApp | UseCalendarAppReturn;
  /** Custom event content renderer for Day view timed events */
  eventContentDay?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for Week view timed events */
  eventContentWeek?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for Month view timed events */
  eventContentMonth?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for Year view events */
  eventContentYear?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for all-day events in Day view */
  eventContentAllDayDay?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for all-day events in Week view */
  eventContentAllDayWeek?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for all-day events in Month view */
  eventContentAllDayMonth?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event content renderer for all-day events in Year view */
  eventContentAllDayYear?: (args: EventContentSlotArgs) => ReactNode;
  /** Custom event detail panel content (React) */
  eventDetailContent?: (args: EventDetailContentProps) => ReactNode;
  /** Custom event detail dialog (React) */
  eventDetailDialog?: (args: EventDetailDialogProps) => ReactNode;
  /** Custom create calendar dialog (React) */
  createCalendarDialog?: (args: CreateCalendarDialogProps) => ReactNode;
  /** Optional left padding to account for safe area insets (e.g. on Mac) */
  collapsedSafeAreaLeft?: number;
  /** Title bar slot (React) */
  titleBarSlot?: (context: TitleBarSlotProps) => ReactNode;
  /** Custom color picker renderer (React) */
  colorPicker?: (args: ColorPickerProps) => ReactNode;
  /** Custom create calendar dialog color picker renderer (React) */
  createCalendarDialogColorPicker?: (
    args: CreateCalendarDialogColorPickerProps
  ) => ReactNode;
}

/** Compute active override names from props and installed plugins. */
function computeActiveOverrides(
  app: ICalendarApp,
  renderProps: Omit<DayFlowCalendarProps, 'calendar'>
): string[] {
  const fromProps = Object.keys(renderProps).filter(
    key => (renderProps as Record<string, unknown>)[key] !== undefined
  );

  const fromPlugins: string[] = [];
  if (app?.state?.plugins) {
    app.state.plugins.forEach(plugin => {
      if (plugin.name === 'sidebar' && plugin.config) {
        const config = plugin.config as Record<string, unknown>;
        if (config['render']) {
          fromPlugins.push('sidebar');
        }
        if (config['renderCreateCalendarDialog']) {
          fromPlugins.push('createCalendarDialog');
        }
        if (config['renderCalendarContextMenu']) {
          fromPlugins.push('calendarContextMenu');
        }
        if (config['renderSidebarHeader']) {
          fromPlugins.push('sidebarHeader');
        }
      }
    });
  }

  return [...new Set([...fromProps, ...fromPlugins])];
}

/** Shallow ordered comparison — avoids JSON.stringify allocation. */
function overridesChanged(prev: string[], next: string[]): boolean {
  return prev.length !== next.length || prev.some((v, i) => v !== next[i]);
}

export const DayFlowCalendar: FC<DayFlowCalendarProps> = ({
  calendar,
  ...renderProps
}: DayFlowCalendarProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const rendererRef = useRef<CalendarRenderer | null>(null);
  const [customRenderings, setCustomRenderings] = useState<
    Map<string, CustomRendering>
  >(new Map());
  const [isMounted, setIsMounted] = useState(false);

  // Extract the underlying app instance
  const app =
    'app' in calendar && calendar.app
      ? calendar.app
      : (calendar as ICalendarApp);
  const renderPropsKeysRef = useRef<string[]>([]);

  useIsomorphicLayoutEffect(() => {
    setIsMounted(true);
    if (!containerRef.current || !app) {
      return;
    }

    // Compute overrides synchronously so the very first Preact render already
    // knows which slots are handled by this adapter — no race window.
    const initialOverrides = computeActiveOverrides(app, renderProps);
    renderPropsKeysRef.current = initialOverrides;

    const renderer = new CalendarRenderer(app, initialOverrides);
    rendererRef.current = renderer;
    renderer.setProps(renderProps);
    renderer.mount(containerRef.current);

    const store = renderer.getCustomRenderingStore();

    const unsubscribeStore = store.subscribe(
      (
        renderings:
          | Iterable<readonly [string, CustomRendering]>
          | null
          | undefined
      ) => {
        setCustomRenderings(new Map(renderings));
      }
    );

    return () => {
      // if React recycles this fiber on the next route.
      store.setOverrides([]);
      unsubscribeStore();
      renderer.unmount();
      rendererRef.current = null;
    };
  }, [app]);

  // Keep overrides and props in sync when they change after the initial mount.
  useEffect(() => {
    if (!rendererRef.current) {
      return;
    }
    const store = rendererRef.current.getCustomRenderingStore();

    const allOverrides = computeActiveOverrides(app, renderProps);
    if (overridesChanged(renderPropsKeysRef.current, allOverrides)) {
      store.setOverrides(allOverrides);
      app.setOverrides(allOverrides);
      renderPropsKeysRef.current = allOverrides;
    }

    rendererRef.current.setProps(renderProps);
  }, [renderProps, app]);

  // Portals for custom content
  const portals = useMemo(() => {
    if (!isMounted) {
      return [];
    }
    return [...customRenderings.values()].map((rendering: CustomRendering) => {
      const { id, containerEl, generatorName, generatorArgs } = rendering;

      // 1. Look up the generator in props
      let generator = (renderProps as Record<string, unknown>)[generatorName];

      // 2. If not in props, look up in plugins
      if (!generator && app && app.state && app.state.plugins) {
        app.state.plugins.forEach(plugin => {
          if (plugin.name === 'sidebar' && plugin.config) {
            const config = plugin.config as Record<string, unknown>;
            switch (generatorName) {
              case 'sidebar':
                generator = config['render'];
                break;
              case 'createCalendarDialog':
                generator = config['renderCreateCalendarDialog'];
                break;
              case 'calendarContextMenu':
                generator = config['renderCalendarContextMenu'];
                break;
              case 'sidebarHeader':
                generator = config['renderSidebarHeader'];
                break;
              default:
                break;
            }
          }
        });
      }

      if (!generator) {
        return null;
      }

      const content =
        typeof generator === 'function' ? generator(generatorArgs) : generator;

      return createPortal(content, containerEl, id);
    });
  }, [customRenderings, renderProps, isMounted, app]);

  return (
    <>
      <div ref={containerRef} className='df-calendar-wrapper' />
      {isMounted && portals}
    </>
  );
};

// packages/angular/src/lib/day-flow-calendar.component.ts
import {
  ElementRef,
  OnChanges,
  OnDestroy,
  AfterViewInit,
  SimpleChanges,
  TemplateRef,
  ChangeDetectorRef,
  Component,
  Input,
  ViewChild,
  ChangeDetectionStrategy,
} from '@angular/core';
import type {
  ICalendarApp,
  CalendarAppConfig,
  CalendarAppConfigSyncSnapshot,
  UseCalendarAppReturn,
  CustomRendering,
  EventDetailContentProps,
  EventDetailDialogProps,
  CreateCalendarDialogProps,
  TitleBarSlotProps,
  EventContentSlotArgs,
  ColorPickerProps,
  CreateCalendarDialogColorPickerProps,
  CalendarHeaderProps,
  EventContextMenuSlotArgs,
  GridContextMenuSlotArgs,
} from '@dayflow/core';
import {
  CalendarRenderer,
  CalendarApp,
  createConfigSyncSnapshot,
  createNormalizedCalendarAppConfigGetter,
  syncCalendarAppConfig,
} from '@dayflow/core';

@Component({
  selector: 'dayflow-calendar',
  template: `
    <div #container class="df-calendar-wrapper"></div>

    <!-- Hidden area to render Angular templates before they are portaled -->
    <div style="display: none">
      <ng-container *ngFor="let rendering of customRenderings; trackBy: trackById">
        <div
          *ngIf="getTemplate(rendering.generatorName)"
          [dayflowPortal]="rendering.containerEl"
        >
          <ng-container
            *ngTemplateOutlet="
              getTemplate(rendering.generatorName)!;
              context: { $implicit: rendering.generatorArgs }
            "
          ></ng-container>
        </div>
      </ng-container>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DayFlowCalendarComponent
  implements AfterViewInit, OnChanges, OnDestroy
{
  @Input() calendar!: ICalendarApp | UseCalendarAppReturn | CalendarAppConfig;

  // Templates for custom content injection
  @Input() eventContentDay?: TemplateRef<EventContentSlotArgs>;
  @Input() eventContentWeek?: TemplateRef<EventContentSlotArgs>;
  @Input() eventContentMonth?: TemplateRef<EventContentSlotArgs>;
  @Input() eventContentYear?: TemplateRef<EventContentSlotArgs>;
  @Input() eventContentAllDayDay?: TemplateRef<EventContentSlotArgs>;
  @Input() eventContentAllDayWeek?: TemplateRef<EventContentSlotArgs>;
  @Input() eventContentAllDayMonth?: TemplateRef<EventContentSlotArgs>;
  @Input() eventContentAllDayYear?: TemplateRef<EventContentSlotArgs>;
  @Input() eventDetailContent?: TemplateRef<EventDetailContentProps>;
  @Input() eventDetailDialog?: TemplateRef<EventDetailDialogProps>;
  @Input() createCalendarDialog?: TemplateRef<CreateCalendarDialogProps>;
  @Input() titleBarSlot?: TemplateRef<TitleBarSlotProps>;
  @Input() colorPicker?: TemplateRef<ColorPickerProps>;
  @Input()
  createCalendarDialogColorPicker?: TemplateRef<CreateCalendarDialogColorPickerProps>;
  @Input() calendarHeader?: TemplateRef<CalendarHeaderProps>;
  @Input() eventContextMenu?: TemplateRef<EventContextMenuSlotArgs>;
  @Input() gridContextMenu?: TemplateRef<GridContextMenuSlotArgs>;
  @Input() collapsedSafeAreaLeft?: number;

  @ViewChild('container') container!: ElementRef<HTMLElement>;

  customRenderings: CustomRendering[] = [];
  private renderer?: CalendarRenderer;
  private unsubscribe?: () => void;
  private internalApp?: CalendarApp;
  private getNormalizedInternalConfig?: () => CalendarAppConfig;
  private internalConfigSyncSnapshot?: CalendarAppConfigSyncSnapshot;

  constructor(private cdr: ChangeDetectorRef) {}

  private get app(): ICalendarApp {
    if (this.internalApp) {
      return this.internalApp;
    }

    if (this.calendar instanceof CalendarApp) {
      return this.calendar;
    }

    if ((this.calendar as { app?: ICalendarApp; views?: unknown[] }).app) {
      return (this.calendar as { app?: ICalendarApp; views?: unknown[] }).app!;
    }

    // If it's a config object, we create an internal instance
    if (DayFlowCalendarComponent.isCalendarConfig(this.calendar)) {
      return this.getOrCreateInternalApp();
    }

    return this.calendar as ICalendarApp;
  }

  ngAfterViewInit() {
    this.initCalendar();
  }

  ngOnChanges(changes: SimpleChanges) {
    if (changes['calendar'] && !changes['calendar'].firstChange) {
      if (this.canSyncInternalCalendarConfig(changes['calendar'])) {
        this.syncInternalCalendarConfig();
      } else {
        this.resetInternalCalendarState();
        this.destroyCalendar();
        this.initCalendar();
      }
    } else if (this.renderer) {
      if (changes['collapsedSafeAreaLeft']) {
        this.renderer.setProps({
          collapsedSafeAreaLeft: this.collapsedSafeAreaLeft,
        });
      }
      const slotKeys = [
        'eventContentDay',
        'eventContentWeek',
        'eventContentMonth',
        'eventContentYear',
        'eventContentAllDayDay',
        'eventContentAllDayWeek',
        'eventContentAllDayMonth',
        'eventContentAllDayYear',
        'eventDetailContent',
        'eventDetailDialog',
        'createCalendarDialog',
        'titleBarSlot',
        'colorPicker',
        'createCalendarDialogColorPicker',
        'calendarHeader',
        'eventContextMenu',
        'gridContextMenu',
      ];
      if (slotKeys.some(key => changes[key])) {
        const activeOverrides = this.getActiveOverrides();
        this.renderer.getCustomRenderingStore().setOverrides(activeOverrides);
        this.app.setOverrides(activeOverrides);
      }
    }
  }

  ngOnDestroy() {
    this.destroyCalendar();
  }

  private initCalendar() {
    if (!this.container || !this.calendar) {
      return;
    }

    const activeOverrides = this.getActiveOverrides();
    this.renderer = new CalendarRenderer(this.app, activeOverrides);
    this.renderer.setProps({
      collapsedSafeAreaLeft: this.collapsedSafeAreaLeft,
    });
    this.renderer.mount(this.container.nativeElement);
    this.app.setOverrides(activeOverrides);

    this.unsubscribe = this.renderer
      .getCustomRenderingStore()
      .subscribe(renderings => {
        this.customRenderings = [...renderings.values()];
        this.cdr.markForCheck();
      });
  }

  private getActiveOverrides(): string[] {
    const templateInputs: Record<string, TemplateRef<unknown> | undefined> = {
      eventContentDay: this.eventContentDay,
      eventContentWeek: this.eventContentWeek,
      eventContentMonth: this.eventContentMonth,
      eventContentYear: this.eventContentYear,
      eventContentAllDayDay: this.eventContentAllDayDay,
      eventContentAllDayWeek: this.eventContentAllDayWeek,
      eventContentAllDayMonth: this.eventContentAllDayMonth,
      eventContentAllDayYear: this.eventContentAllDayYear,
      eventDetailContent: this.eventDetailContent,
      eventDetailDialog: this.eventDetailDialog,
      createCalendarDialog: this.createCalendarDialog,
      titleBarSlot: this.titleBarSlot,
      colorPicker: this.colorPicker,
      createCalendarDialogColorPicker: this.createCalendarDialogColorPicker,
      calendarHeader: this.calendarHeader,
      eventContextMenu: this.eventContextMenu,
      gridContextMenu: this.gridContextMenu,
    };
    return Object.keys(templateInputs).filter(
      key => templateInputs[key] !== null && templateInputs[key] !== undefined
    );
  }

  private destroyCalendar() {
    if (this.unsubscribe) {
      this.unsubscribe();
    }
    if (this.renderer) {
      this.renderer.unmount();
    }
    this.unsubscribe = undefined;
    this.renderer = undefined;
  }

  private static isCalendarConfig(value: unknown): value is CalendarAppConfig {
    return (
      !!value &&
      typeof value === 'object' &&
      'views' in value &&
      !('app' in value)
    );
  }

  private getOrCreateInternalApp(): CalendarApp {
    if (!this.internalApp) {
      this.getNormalizedInternalConfig =
        createNormalizedCalendarAppConfigGetter(
          () => this.calendar as CalendarAppConfig
        );
      const normalizedConfig = this.getNormalizedInternalConfig();
      this.internalApp = new CalendarApp(normalizedConfig);
      this.internalConfigSyncSnapshot =
        createConfigSyncSnapshot(normalizedConfig);
    }

    return this.internalApp;
  }

  private canSyncInternalCalendarConfig(
    change: SimpleChanges['calendar']
  ): boolean {
    return (
      DayFlowCalendarComponent.isCalendarConfig(change.currentValue) &&
      DayFlowCalendarComponent.isCalendarConfig(change.previousValue) &&
      !!this.internalApp &&
      !!this.getNormalizedInternalConfig &&
      !!this.internalConfigSyncSnapshot
    );
  }

  private syncInternalCalendarConfig() {
    if (
      !this.internalApp ||
      !this.getNormalizedInternalConfig ||
      !this.internalConfigSyncSnapshot
    ) {
      return;
    }

    this.internalConfigSyncSnapshot = syncCalendarAppConfig(
      this.internalApp,
      this.internalConfigSyncSnapshot,
      this.getNormalizedInternalConfig()
    );
  }

  private resetInternalCalendarState() {
    this.internalApp = undefined;
    this.getNormalizedInternalConfig = undefined;
    this.internalConfigSyncSnapshot = undefined;
  }

  getTemplate(name: string): TemplateRef<unknown> | null {
    // Switch avoids allocating a new Record on every change-detection cycle.
    switch (name) {
      case 'eventContentDay': {
        return this.eventContentDay ?? null;
      }
      case 'eventContentWeek': {
        return this.eventContentWeek ?? null;
      }
      case 'eventContentMonth': {
        return this.eventContentMonth ?? null;
      }
      case 'eventContentYear': {
        return this.eventContentYear ?? null;
      }
      case 'eventContentAllDayDay': {
        return this.eventContentAllDayDay ?? null;
      }
      case 'eventContentAllDayWeek': {
        return this.eventContentAllDayWeek ?? null;
      }
      case 'eventContentAllDayMonth': {
        return this.eventContentAllDayMonth ?? null;
      }
      case 'eventContentAllDayYear': {
        return this.eventContentAllDayYear ?? null;
      }
      case 'eventDetailContent': {
        return this.eventDetailContent ?? null;
      }
      case 'eventDetailDialog': {
        return this.eventDetailDialog ?? null;
      }
      case 'createCalendarDialog': {
        return this.createCalendarDialog ?? null;
      }
      case 'titleBarSlot': {
        return this.titleBarSlot ?? null;
      }
      case 'colorPicker': {
        return this.colorPicker ?? null;
      }
      case 'createCalendarDialogColorPicker': {
        return this.createCalendarDialogColorPicker ?? null;
      }
      case 'calendarHeader': {
        return this.calendarHeader ?? null;
      }
      case 'eventContextMenu': {
        return this.eventContextMenu ?? null;
      }
      case 'gridContextMenu': {
        return this.gridContextMenu ?? null;
      }
      default: {
        return null;
      }
    }
  }

  // eslint-disable-next-line class-methods-use-this
  trackById(_index: number, item: CustomRendering) {
    return item.id;
  }
}
